[package]
name = "message_gate"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
alloy-sol-types = {version="0.6.3"}
[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
